### ISSUE TITLE
Upgrade NumPy dependency

### ISSUE THREAD

**Issue by gresavage** [act3-ace/safe-autonomy-sims#31]
NumPy is pinned to `1.24.0` and there are significant changes to `numpy.random` between `1.24.0` and `1.25.0` (mostly how attributes are accessed)

We programmed against `1.25.0` so having to refactor our code-base just to access the methods and attributes of `numpy.random.BitGenerators` etc. in the `1.24.0` paradigm is very frustrating.

We have force-installed `1.25.0` and everything seems to work fine with sa-sims so I don't think the strict equality dependency is necessary... it will probably suffice just to pin `numpy = "^1.24.0"` in `pyproject.toml`

**Comment by jamie-cunningham** [comment]
Yes, this solution seems to work just fine. I've opened a PR and it should be good to merge.
